### PR TITLE
Fix symlink creation in composer installer

### PR DESCRIPTION
**Pull request by IchHabRecht**
This patch ensures the realpath fallback is used, if symlink()
fails for the first time. On Windows systems symlink() throws an
ErrorException if the source cannot be verified.

Fixes: #65

### CODE REVIEW

**Comment by aimeos** [comment]
Thanks for the hint. PHP symlink docs say nothing about throwing an ErrorException. Maybe this is caused by PHP triggering a warning or notice. Does
```
if( file_exists( $target ) === false && @symlink( $source, $target ) === false )
```
also work (if "@" silence operator is added)?

**Comment by IchHabRecht** [comment]
I didn't found anything about the Exception neither but can confirm it is thrown because of a wrong $source input on Windows systems. Adding '@' also works but I thought (thanks to a hint of @jfastnacht) it is better to catch that explicitly (now known) error.

**Comment by aimeos** [comment]
As the ErrorException seems to be only a indirect and undocumented cause of the trigger_error() method used by symlink(), I won't rely on that. Also, using "@" leads to a much more elegant code so I would prefer that.

Can you adapt your PR?

**Comment by IchHabRecht** [comment]
Currently on the run, but you are able to edit the pull request as you like. I wouldn't suppress any other undocumented error, that why I introduced to catch only the known one. I find this is the more elegant solution for this very specific problem but don't mind if you change the code.

**Comment by aimeos** [comment]
OK. Thanks for your support!

**Pull request merged**
