### PR TITLE
Changed language and currency parameter names to defaults TYPO3 locale

### PR DESCRIPTION
**Pull request by gilbertsoft**
Language / currency selector does not run because different names in locale.php. So I created a new default config for TYPO3 to not touch other distros

### CODE REVIEW

**Comment by aimeos** [comment]
We've tried to streamline the parameter names for language and currency but that wasn't the case for TYPO3 up to now. Can you try the current dev-master branch (aimeos-typo3 and ai-client-html)? It contains the necessary change and will use "locale" (languageid) and "currency" like in the other integrations.

**Comment by gilbertsoft** [comment]
Yes, I saw. But don't you need to redefine the params for the html-client to? Have a look at Aimeos\Client\Html\Locale\Select\Standard

**Comment by aimeos** [comment]
Yes, that's already the case in dev-master:
https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Locale/Select/Standard.php#L337

**Comment by gilbertsoft** [comment]
Great, so this PR could be closed too I think? Because I only know the T3 impl I thought it's better only changing the extension and no global code ;-)

**Pull request closed without merging**
