### PR TITLE
Deploy optimizations

### PR DESCRIPTION
**Pull request by gilbertsoft**
I had a look at your new build file and merged some configurations of a own T3 ext. Hope there are no copy / paste errors, did not test it but checked it twice.

Is there a reason not using the zip, git and composer tasks instead of exec? I don't have experiences with git and composer but I'm successfull using the zip task.

### CODE REVIEW

**Comment by aimeos** [comment]
The main problem of your changes is that you rely on an external properties file. This will lead to use the values from an outdated file on `phing deploy`.

Maybe using `exec` was the safest option years ago.

**Comment by gilbertsoft** [comment]
In which order do you call the targets (release, deploy)?

**Comment by aimeos** [comment]
Most of the time `phing deploy` is independent from `phing release` because we usually create a lot of "-preX" versions before releasing an official one.

**Comment by gilbertsoft** [comment]
Ok, I see. I'm currently optimizing my own build scripts with a built in upload to TER etc. I'll merge this changes including a prompt at the deploy target a.s.a.p.

I think the approach storing the properties to a properties file is a good choice for you too, so you'll have all relevant data at the repo.

**Comment by aimeos** [comment]
We have the deployment process under control now with the current deploy target.

**Pull request closed without merging**
