### PR TITLE
Use symfony/thanks for staring the repository

### PR DESCRIPTION
**Pull request by gilbertsoft**
This fixes an issue where on each call a Github token is requested.
Instead of rely on a own implementation symfony/thanks is now
used.

### CODE REVIEW

**Comment by gilbertsoft** [comment]
Will have to check this one first, not sure if it's fine to require symfony/thanks here....

**Comment by aimeos** [comment]
Like discussed in Slack, symfony/thanks should not be required.

**Comment by rowild** [comment]
This discussion was obviously private. Any chance to share as to why it should not be required?

**Comment by gilbertsoft** [comment]
We will provide a fix for the current solution a.s.a.p.

**Comment by aimeos** [comment]
We've added a check so it won't do anything until you've configured it:
https://github.com/aimeos/aimeos-typo3/commit/4c56ce6337c8a38d41a42c384c1f1fce1cdd4ac4

**Pull request closed without merging**
